config/routes.rb
# == Route Map
#
#                                   Prefix Verb     URI Pattern                                           Controller#Action
#                               blacklight          /finding-aids                                         Blacklight::Engine
#                          arclight_engine          /finding-aids                                         Arclight::Engine
#               yabeda_prometheus_exporter          /finding-aids/metrics                                 Yabeda::Prometheus::Exporter
#                           search_catalog GET|POST /finding-aids/catalog(.:format)                       catalog#index
#                  advanced_search_catalog GET      /finding-aids/catalog/advanced(.:format)              catalog#advanced_search
#                       page_links_catalog GET      /finding-aids/catalog/page_links(.:format)            catalog#page_links
#                            track_catalog POST     /finding-aids/catalog/:id/track(.:format)             catalog#track
#                              raw_catalog GET      /finding-aids/catalog/:id/raw(.:format)               catalog#raw {:format=>"json"}
#                       opensearch_catalog GET      /finding-aids/catalog/opensearch(.:format)            catalog#opensearch
#                    suggest_index_catalog GET      /finding-aids/catalog/suggest(.:format)               catalog#suggest
#                            facet_catalog GET      /finding-aids/catalog/facet/:id(.:format)             catalog#facet
#                      range_limit_catalog GET      /finding-aids/catalog/range_limit(.:format)           catalog#range_limit
#                                          GET      /finding-aids/catalog/range_limit_panel/:id(.:format) catalog#range_limit_panel
#                  hierarchy_solr_document GET      /finding-aids/catalog/:id/hierarchy(.:format)         catalog#hierarchy
#                      email_solr_document GET|POST /finding-aids/catalog/:id/email(.:format)             catalog#email
#                        sms_solr_document GET|POST /finding-aids/catalog/:id/sms(.:format)               catalog#sms
#                   citation_solr_document GET      /finding-aids/catalog/:id/citation(.:format)          catalog#citation
#                     email_solr_documents GET|POST /finding-aids/catalog/email(.:format)                 catalog#email
#                       sms_solr_documents GET|POST /finding-aids/catalog/sms(.:format)                   catalog#sms
#                  citation_solr_documents GET      /finding-aids/catalog/citation(.:format)              catalog#citation
#                            solr_document GET      /finding-aids/catalog/:id(.:format)                   catalog#show
#                           email_bookmark GET|POST /finding-aids/bookmarks/:id/email(.:format)           bookmarks#email
#                             sms_bookmark GET|POST /finding-aids/bookmarks/:id/sms(.:format)             bookmarks#sms
#                        citation_bookmark GET      /finding-aids/bookmarks/:id/citation(.:format)        bookmarks#citation
#                          email_bookmarks GET|POST /finding-aids/bookmarks/email(.:format)               bookmarks#email
#                            sms_bookmarks GET|POST /finding-aids/bookmarks/sms(.:format)                 bookmarks#sms
#                       citation_bookmarks GET      /finding-aids/bookmarks/citation(.:format)            bookmarks#citation
#                          clear_bookmarks DELETE   /finding-aids/bookmarks/clear(.:format)               bookmarks#clear
#                                bookmarks GET      /finding-aids/bookmarks(.:format)                     bookmarks#index
#                                          POST     /finding-aids/bookmarks(.:format)                     bookmarks#create
#                             new_bookmark GET      /finding-aids/bookmarks/new(.:format)                 bookmarks#new
#                            edit_bookmark GET      /finding-aids/bookmarks/:id/edit(.:format)            bookmarks#edit
#                                 bookmark GET      /finding-aids/bookmarks/:id(.:format)                 bookmarks#show
#                                          PATCH    /finding-aids/bookmarks/:id(.:format)                 bookmarks#update
#                                          PUT      /finding-aids/bookmarks/:id(.:format)                 bookmarks#update
#                                          DELETE   /finding-aids/bookmarks/:id(.:format)                 bookmarks#destroy
#                         email_2fa_enable GET      /finding-aids/email_2fa/enable(.:format)              email2fa#enable
#                        email_2fa_disable GET      /finding-aids/email_2fa/disable(.:format)             email2fa#disable
#                          email_2fa_alert GET      /finding-aids/email_2fa/alert(.:format)               email2fa_alert#show
#                  email_2fa_alert_dismiss GET      /finding-aids/email_2fa/alert/dismiss(.:format)       email2fa_alert#dismiss
#                                     root GET      /finding-aids(.:format)                               catalog#index {:f=>{:level=>["Collection"], :repository=>["National Library of Australia"]}}
#                                          GET      /                                                     redirect(301, /finding-aids)
# user_catalogue_patron_omniauth_authorize GET|POST /users/auth/catalogue_patron(.:format)                users/omniauth_callbacks#passthru
#  user_catalogue_patron_omniauth_callback GET|POST /users/auth/catalogue_patron/callback(.:format)       users/omniauth_callbacks#catalogue_patron
#    user_catalogue_sol_omniauth_authorize GET|POST /users/auth/catalogue_sol(.:format)                   users/omniauth_callbacks#passthru
#     user_catalogue_sol_omniauth_callback GET|POST /users/auth/catalogue_sol/callback(.:format)          users/omniauth_callbacks#catalogue_sol
#    user_catalogue_spl_omniauth_authorize GET|POST /users/auth/catalogue_spl(.:format)                   users/omniauth_callbacks#passthru
#     user_catalogue_spl_omniauth_callback GET|POST /users/auth/catalogue_spl/callback(.:format)          users/omniauth_callbacks#catalogue_spl
# user_catalogue_shared_omniauth_authorize GET|POST /users/auth/catalogue_shared(.:format)                users/omniauth_callbacks#passthru
#  user_catalogue_shared_omniauth_callback GET|POST /users/auth/catalogue_shared/callback(.:format)       users/omniauth_callbacks#catalogue_shared
#                         new_user_session GET      /sign_in(.:format)                                    users/sessions#new
#                     destroy_user_session DELETE   /sign_out(.:format)                                   users/sessions#destroy
#                                   logout GET      /logout(.:format)                                     users/sessions#destroy
#                  expired_keycloak_logout GET      /expired_keycloak_logout(.:format)                    users/sessions#expired_keycloak_logout
#                       backchannel_logout POST     /backchannel_logout(.:format)                         users/sessions#backchannel_logout
#         turbo_recede_historical_location GET      /recede_historical_location(.:format)                 turbo/native/navigation#recede
#         turbo_resume_historical_location GET      /resume_historical_location(.:format)                 turbo/native/navigation#resume
#        turbo_refresh_historical_location GET      /refresh_historical_location(.:format)                turbo/native/navigation#refresh
#
# Routes for Blacklight::Engine:
#       search_history GET    /search_history(.:format)       search_history#index
# clear_search_history DELETE /search_history/clear(.:format) search_history#clear
#
# Routes for Arclight::Engine:
#  collections GET  /collections(.:format)      catalog#index {:f=>{:level=>["Collection"]}}
# repositories GET  /repositories(.:format)     arclight/repositories#index
#   repository GET  /repositories/:id(.:format) arclight/repositories#show

Rails.application.routes.draw do
  scope(path: "/finding-aids") do
    mount Blacklight::Engine => "/"
    mount Arclight::Engine => "/"
    mount Yabeda::Prometheus::Exporter => "/metrics"

    concern :searchable, Blacklight::Routes::Searchable.new
    concern :exportable, Blacklight::Routes::Exportable.new
    concern :hierarchy, Arclight::Routes::Hierarchy.new
    concern :range_searchable, BlacklightRangeLimit::Routes::RangeSearchable.new
    concern :email2fa, Nla::BlacklightCommon::Routes::Email2fa.new

    resource :catalog, as: "catalog", path: "/catalog", controller: "catalog" do
      concerns :searchable
      concerns :range_searchable
    end

    resources :solr_documents, only: [:show], path: "/catalog", controller: "catalog" do
      concerns :hierarchy
      concerns :exportable
    end

    resources :bookmarks do
      concerns :exportable

      collection do
        delete "clear"
      end
    end

    concerns :email2fa

    # Show repostories with information about each
    # root to: "arclight/repositories#index"

    # Show first 100 NLA collections
    # root to: "arclight/repositories#show", id: "nla"

    # Show search for NLA collections
    root to: "catalog#index", defaults: {f: {level: ["Collection"], repository: ["National Library of Australia"]}}
  end

  scope path: "/account", as: "account" do
    get "/requests", to: "account#requests"
    get "/requests/:request_id", to: "account#request_details", as: "request_details"
    scope path: "/profile", as: "profile" do
      get "/", to: "account#profile"
      get "/edit", to: "account#profile_edit"
      post "/edit", to: "account#profile_update"
    end
  end

  get "/", to: redirect("/finding-aids")
end

app/views/shared/_footer.html.erb
<footer class="footer mt-auto d-print-none">
  <section class="footer-ask-a-librarian text-center">
    <div class="arrow-tip" aria-hidden="true">
      <svg xmlns="http://www.w3.org/2000/svg" width="55" height="18" viewBox="0 0 55 18" fill="none">
        <style>
          #arrow-tip {
              fill: #FFFFFF;
          }
                  
          @media screen and (prefers-color-scheme: dark) {
              #arrow-tip {
                  fill: #000000;
              }
          }
      </style>
        <path d="M54.5039 0.000494003L0.00132598 0.000494955C12.3289 0.000493877 21.7123 6.92791 27.2526 17.5313C32.7756 6.96093 42.2449 0.000495075 54.5039 0.000494003Z" id="arrow-tip"></path>
      </svg>
    </div>
    <h2 class="h2 mb-3"><%= t('blacklight.footer.ask_a_librarian.title') %></h2>
    <div class="mb-3"><%= t("blacklight.footer.ask_a_librarian.description") %></div>
    <div>
      <%= link_to t("blacklight.footer.ask_a_librarian.button"), "https://www.library.gov.au/services/ask-librarian", class: "btn btn-secondary mt-3" %>
    </div>
  </section>
  <div class="footer-top">
    <div class="<%= container_classes %> footer-container">
      <div class="row">
        <div class="col-lg-4 mb-5">
          <section class="opening-hours">
            <h2 class="h4 mb-4"><%= t('blacklight.footer.opening_hours.title') %></h2>
            <p><%= t('blacklight.footer.opening_hours.description') %></p>
            <div><%= link_to t("blacklight.footer.opening_hours.more_opening_hours"), "https://www.library.gov.au/visit/opening-hours", class: "btn btn-tertiary mt-4" %></div>
          </section>
        </div>
        <div class="col-lg-4 mb-5">
          <section class="contact">
            <h2 class="h4 mb-4"><%= t('blacklight.footer.contact.title') %></h2>
            <p>
              <%= link_to t("blacklight.footer.contact.telephone"), "tel:+61262621111" %><br>
              <%= t('blacklight.footer.contact.address').html_safe %>
            </p>
            <div><%= link_to t("blacklight.footer.contact.more_contact_info"), "https://www.library.gov.au/services/contact-us", class: "btn btn-tertiary mt-2 mb-5" %></div>
          </section>
          <section class="connect">
            <h2 class="h4 mb-4"><%= t('blacklight.footer.connect.title') %></h2>
            <ul class="list-inline">
              <li class="list-inline-item pe-4">
                  <a href="https://www.facebook.com/National.Library.of.Australia">
                      <i class="fa-brands fa-facebook fa-2x" aria-hidden="true"></i>
                      <span class="sr-only">Facebook</span>
                  </a>
              </li>
              <li class="list-inline-item pe-4">
                  <a href="https://www.instagram.com/nationallibraryaus/">
                      <i class="fa-brands fa-instagram fa-2x" aria-hidden="true"></i>
                      <span class="sr-only">Instagram</span>
                  </a>
              </li>
              <li class="list-inline-item pe-4">
                  <a href="https://www.youtube.com/channel/UCv51AT4rmiwH1M9aLDE1AIA">
                      <i class="fa-brands fa-youtube fa-2x" aria-hidden="true"></i>
                      <span class="sr-only">YouTube</span>
                  </a>
              </li>
            </ul>
            <div>
              <%= link_to t("blacklight.footer.connect.enews"), "https://www.library.gov.au/services/contact-us/subscribe-our-newsletters", class: "btn btn-tertiary mt-2" %>
            </div>
          </section>
        </div>
        <div class="col-lg-4">
          <section class="acknowledgement">
            <h2 class="h4 mb-4"><%= t('blacklight.footer.acknowledgement_of_country.title') %></h2>
              <p><%= t('blacklight.footer.acknowledgement_of_country.description.p1') %></p>
                <p><%= t('blacklight.footer.acknowledgement_of_country.description.p2') %></p>
                </p>
          </section>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-bottom py-4">
    <div class="<%= container_classes %>">
      <div class="row">
        <ul class="primary-links mb-4">
            <li>
              <%= link_to t("blacklight.footer.primary_links.discover"), "https://www.library.gov.au/discover" %>
            </li>
            <li>
              <%= link_to t("blacklight.footer.primary_links.research"), "https://www.library.gov.au/research" %>
            </li>
            <li>
              <%= link_to t("blacklight.footer.primary_links.visit"), "https://www.library.gov.au/visit" %>
            </li>
        </ul>
        <ul class="secondary-links mb-5">
            <li>
              <%= link_to t("blacklight.footer.secondary_links.privacy"), "https://www.library.gov.au/visit/about-website/privacy" %>
            </li>
            <li><%= link_to t("blacklight.footer.secondary_links.disclaimer"), "https://www.library.gov.au/visit/about-website/disclaimer" %>
            </li>
            <li><%= link_to t("blacklight.footer.secondary_links.terms"), "https://www.library.gov.au/visit/about-website/terms-and-conditions" %>
            </li>
        </ul>
      </div>
      <div class="row">
        <section class="text-center footer-logo mt-3">
          <%= link_to image_tag("nla-stacked-logo-black.svg", :alt => "National Library of Australia logo", :width => "134", :height => "111", class: "logo"), "https://www.library.gov.au" %>
        </section>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_user_util_links.html.erb
<ul class="navbar-nav">
  <%= render_nav_actions do |config, action|%>
    <li class="nav-item"><%= action %></li>
  <% end %>
  <% if has_user_authentication_provider? %>
    <% if current_user %>
      <li class="nav-item dropdown">
        <%= link_to current_user, "#", class: "nav-link dropdown-toggle #{active_link_class_controller(%w[bookmarks])}", id: "navbarDropdown", role: "button", data: {'bs-toggle': "dropdown"}, aria: {haspopup: "true", expanded: "false"} %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to t("blacklight.account.requests.menu"), account_requests_path, class: "dropdown-item" %>
          <%= render partial: "blacklight/nav/bookmark" %>
          <%= link_to t("blacklight.account.settings.menu"), account_profile_path, class: "dropdown-item" %>
          <%= button_to t('blacklight.header_links.logout'), destroy_user_session_path, class: 'dropdown-item', method: :delete, data: { turbo: false } %>
        </div>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to t("blacklight.header_links.register"), "https://www.library.gov.au/research/join-library", class: "nav-link" %>
      </li>
      <% unless ENV["FOLIO_UPDATE_IN_PROGRESS"] == "true" %>
        <li class="nav-item">
          <%= link_to t('blacklight.header_links.login'), new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
    <% end %>
  <% end %>
</ul>